In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Load dataset (replace with actual library dataset if available)
data = {
    'Book_ID': np.arange(1, 11),
    'Pages': np.random.randint(100, 500, 10),
    'Genre': np.random.choice(['Fiction', 'Non-Fiction', 'Science', 'History'], 10),
    'Borrowed_Times': np.random.randint(1, 20, 10),
    'Popular': np.random.choice([0, 1], 10)  # Target: 1 if popular, 0 if not
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert categorical column 'Genre' to numerical
df = pd.get_dummies(df, columns=['Genre'], drop_first=True)

# Display first few rows
df.head()

,Book_ID,Pages,Borrowed_Times,Popular,Genre_History,Genre_Non-Fiction,Genre_Science
0,1,126,15,1,False,True,False
1,2,435,12,1,False,True,False
2,3,474,11,0,False,False,True
3,4,418,15,0,True,False,False
4,5,373,17,1,False,False,False

In [3]:
# Split features and target variable
X = df.drop(columns=['Book_ID', 'Popular'])  # Book_ID is irrelevant
y = df['Popular']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling (KNN is distance-based, so scaling is important)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train KNN model
knn_model = KNeighborsClassifier(n_neighbors=3)  # You can change k (n_neighbors)
knn_model.fit(X_train, y_train)

# Predict and evaluate
y_pred = knn_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"KNN Accuracy: {accuracy:.2f}")

KNN Accuracy: 0.00